import '../styles/globals.css'

export const metadata = {
  title: 'DevTony',
  description: 'Generated by create next app',
  keywords:'Next.js,React,JavaScript,CSS,HTML,TailwindCss,Frontend,Developer,Web,Fullstack,devtony,devtony.me,DevTony,anthony molina,Anthony Molina Meriño,anthony,molina,Meriño,Anthony Molina,portfolio,portafolio,projects,proyectos,skills,habilidades,about,sobre,contact,contacto,contactame,contactame,contact me',
  authors: { name: 'Anthony Molina', url: 'https://devtony.me' },
  creator: 'Anthony Molina',
  twitter: {
    card: 'summary_large_image',
    title: 'Dev Tony | Frontend Developer',
    creator: '@devtony25',
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#1F2937]">{children}
      </body>
    </html>
  )
}